import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from 'react'
import Sidebar from '@/components/layout/sidebar'
import Header from '@/components/layout/header'
import { SidebarProvider } from '@/contexts/SidebarContext'
import { AuthProvider } from '@/contexts/AuthContext'
import { ThemeProvider } from '@/components/theme-provider'
import { Toaster } from 'sonner'
import NavbarHome from "@/components/homenavbar";
import { SessionProvider } from "next-auth/react";
import { NextAuthProvider } from "@/contexts/NextAuthProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <ThemeProvider>
          <AuthProvider>
            <LayoutContent>{children}</LayoutContent>
            <Toaster position="top-right" richColors />
          </AuthProvider>
        </ThemeProvider>
      </body> 
    </html>
  );
}

function LayoutContent({ children }: { children: React.ReactNode }) {
  return (
    <NextAuthProvider>
      <SidebarProvider>
        <div className="flex h-screen bg-background overflow-hidden">
          {/* Sidebar */}
          <NavbarHome />
          <div className="fixed inset-y-0 left-0 z-30 lg:relative lg:z-auto">
            <Sidebar />
          </div>
          {/* Main content */}
          <div className="flex flex-col flex-1 w-full overflow-hidden">
            <Header />
            
            <main className="flex-1 overflow-y-auto p-4 sm:p-6 bg-neutral-50 dark:bg-neutral-900">
              {children}
            </main>
          </div>
        </div>
      </SidebarProvider>
    </NextAuthProvider>
  );
}
